# Generated by Django 6.0.4 on 2026-05-05 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanish', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['-last_practice']},
        ),
        migrations.AddField(
            model_name='userprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprogress',
            name='netid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
