# Generated by Django 6.0.4 on 2026-05-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanish', '0002_alter_userprogress_options_userprogress_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='last_visit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
