# Generated by Django 6.0.4 on 2026-09-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spanish", "0003_userprogress_last_visit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[("essay", "Essay"), ("audio", "Audio")], max_length=10
                    ),
                ),
                ("task", models.JSONField(default=dict)),
                ("text", models.TextField(blank=True)),
                ("result", models.JSONField()),
                ("total_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
