# Generated by Django 6.0.4 on 2026-09-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spanish", "0004_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="duration_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
