# Generated by Django 6.0.4 on 2026-10-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spanish", "0005_submission_duration_seconds"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=10)),
                ("task_type", models.CharField(blank=True, max_length=20)),
                ("level", models.CharField(max_length=5)),
                ("task", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["kind", "task_type", "level"],
                        name="spanish_pro_kind_6f6693_idx",
                    )
                ],
            },
        ),
    ]
